# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|                             
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.provision "shell", inline: "apt-get install -y apache2"
    ubuntu.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    ubuntu.vm.provider "virtualbox" do |vb|
        vb.name = "Ubuntu VM"
    end
  end
  config.vm.define "centos" do |centos| 
    centos.vm.box = "centos/7"
    centos.vm.provider "virtualbox" do |vb|
        vb.name = "Centos VM"
    end
  end
end
