# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|                             
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    config.vm.provision "shell", path: "wordpress-mysql.sh"
    ubuntu.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    ubuntu.vm.provider "virtualbox" do |vb|
        vb.name = "Ubuntu VM"
        vb.memory = "3048"
    end
  end
end
